spring.application.name=indika-ai-assessment
server.port=8080
spring.docker.compose.enabled=false
spring.cache.type=none
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
  org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
spring.datasource.url=jdbc:h2:mem:indikadb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.open-in-view=false
spring.jackson.serialization.write-dates-as-timestamps=false

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.ollama.embedding.options.model=nomic-embed-text
openai.api-key=dummy-key

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.main.allow-bean-definition-overriding=true